### ISSUE TITLE
Create a staging version for all endpoints 

### ISSUE THREAD

**Issue by rodrigoperazzo** [DiscordTime/sticky-sessions-server#42]
Server implementation could have a staging prefix to be used on apps during their development to avoid mixing real sessions and notes with the test ones.

From app point of view, it could be something: 

- production: http://address/endpoint
- staging: http://address/staging/endpoint

**Comment by rodrigoperazzo** [comment]
Right now, it could be implemented by just using another set of collections on the same firebase account.

**Comment by CarlosRodrigo** [comment]
After Continuous Deploy was configured in #56 in now have staging running on port 5000 and production running on port 3000.

@rodrigoperazzo do you think we can close this issue?
